- name: Add Jenkins repository
  become: true
  yum_repository:
    name: jenkins
    description: Jenkins repository
    baseurl: http://pkg.jenkins.io/redhat
    gpgkey: https://jenkins-ci.org/redhat/jenkins-ci.org.key

- name: Install Jenkins
  become: true
  yum:
    name: jenkins
    state: latest
    update_cache: yes
