- name: Install tar
  become: true
  yum:
    name: tar
    state: latest
    update_cache: yes
  when: ansible_pkg_mgr == 'yum'

- name: Disable SELinux
  become: true
  selinux:
    state: disabled
  notify: "Reboot needed"